name: Welcome new contributors
'on':
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send welcome message for PRs
        if: github.event_name == 'pull_request_target'
        run: "echo \"\U0001F389 Thank you @${{ github.actor }} for your first Pull Request! We appreciate your contribution. \U0001F680\"\n"
      - name: Send welcome message for Issues
        if: github.event_name == 'issues'
        run: "echo \"\U0001F44B Hi @${{ github.actor }}! Thanks for opening your first issue here. We'll take a look soon!\"\n"
